.TH 7DATE 1 "661.2015"
.SH NAME
7date \- display the date in the 7date calendar
.SH SYNOPSIS
.B 7date [\-d]
[
.I filename
]
.SH DESCRIPTION
When
.B 7date
is called without a \fIfilename\fR,
it prints the current date in the 7date calendar.
This is the day of the year - starting with 1 for January 1st - written in
base-7 followed by the year. For example, January 31st 2026 is written as
43.2026 since 43 is the base-7 notation for the base-10 number 31.
February 1st 2026, being the 32nd day of the year, is written as 44.2026.
.PP
When a filename is given, the modification time of that file is used to
determine the date printed.
.PP
When the \-d option is provided, the 7date's digital notation is given. For
example, February 1st 2026 is written as 2026-0044. This notation has fixed
length and all digits are in order by descending significance. This makes it
easier to sort or filter such 7dates when they're stored as part of a list.
.SH AUTHORS
Tyler Neylon <tylerneylon@gmail.com>
